export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const MOST_READ_BOOKS_REQUEST = "MOST_READ_BOOKS_REQUEST";
export const MOST_READ_BOOKS_SUCCESS = "MOST_READ_BOOKS_SUCCESS";
export const TRENDING_BOOKS_REQUEST = "TRENDING_BOOKS_REQUEST";
export const TRENDING_BOOKS_SUCCESS = "TRENDING_BOOKS_SUCCESS";